[tool.black]
line-length = 79
target-version = ["py312"]
exclude = '''
/(
  \.git
  | venv
  | migrations
  | node_modules
)/
'''


[tool.ruff]
target-version = "py312"
exclude        = [".git", "venv", "migrations", "node_modules"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501"]        # Line length is controlled by Black
