[general]
model = "gpt-4"

[prompts]
role_prompt = "You are a friendly assistant who has a vast knowledge of customer support chats."
instructions = """
Remove personally identifyable information, only show the date, and replace all swear words with "😤"
"""
instructions_2 = """
Sanitize the text provided in >>>CONTENT<<< in multiple steps:

1. Remove personally identifyable information by replacing names in [] with "Agent" and "Client", respectively
2. Replace the date-time information to only show the date in the format YYYY-mm-dd
3. Replace all swear words with the following emoji: "😤"
"""
instructions_3 = """
Sanitize the text provided in >>>CONTENT<<< in multiple steps:

1. Replace names in [] with "A", for Agent, and "C", for Client, respectively
2. Replace any other personally identifyable information, such as names or email addresses
3. Replace the date-time information to only show the date in the format YYYY-mm-dd
4. Replace all swear words with the following emoji: "😤"
"""
instructions_4 = """
Sanitize the text provided in >>>CONTENT<<< in multiple steps:

1. Replace names in [] with "A", for Agent, and "C", for Client, respectively
2. Replace any other personally identifyable information, such as names or email addresses
3. Replace the date-time information to only show the date in the format YYYY-mm-dd
4. Replace all swear words with the following emoji: "😤"

Here is some example output in the expected format:

2021-09-29:
----------------------------------------------
Agent: How can I assist you today?
Client: I CAN'T GET THIS 😤 THING TO TURN ON!!


2022-02-24:
----------------------------------------------
Agent: Good morning! How can I help you today?
Client: Could you help me with applying my coupon code?
"""
instructions_5 = """
Sanitize the text provided in >>>CONTENT<<< in multiple steps:

1. Replace names in [] with "A", for Agent, and "C", for Client, respectively
2. Replace any other personally identifyable information, such as names or email addresses
3. Replace the date-time information to only show the date in the format YYYY-mm-dd
4. Classify the sentiment of the client's responses in the conversation with "🔥" for negative and "✅" for positive
5. Replace all swear words with the following emoji: "😤"

Here is some example output in the expected format:

🔥 2021-09-29:
----------------------------------------------
A: How can I assist you today?
C: I CAN'T GET THIS 😤 THING TO TURN ON!!


✅ 2022-02-24:
----------------------------------------------
A: Good morning! How can I help you today?
C: Could you help me with applying my coupon code?
"""
instructions_6 = """
Sanitize the text provided in >>>CONTENT<<< in multiple steps:

1. Replace names in [] with "A", for Agent, and "C", for Client, respectively
2. Replace any other personally identifyable information, such as names or email addresses
3. Replace the date-time information to only show the date in the format YYYY-mm-dd
4. Classify the sentiment of the client's responses in the conversation as "negative" and "positive"
5. Replace all swear words with the following emoji: "😤"
6. Format the resulting text as JSON

Here is some example output in the expected JSON format:

```json
{
    "negative": [
        {
            "date": "2021-09-29",
            "conversation": [
                "A: How can I assist you today?",
                "C: I CAN'T GET THIS 😤 THING TO TURN ON!!"
            ]
        },
        ]
    "positive": [
        {
            "date": "2022-02-24",
            "conversation": [
                "A: Good morning! How can I help you today?",
                "C: Could you help me with applying my coupon code?"
            ]
        },
        ]
}
```
"""