[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "snake-shop-ordering"
version = "2.1.0"
description = "Ordering Package for the Snake Shop Corporation"
license = {text = "Snake Shop Software Licence Agreement"}

[tool.black]
line-length=79