[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "snake-corp-dateutil"
version = "1.0.3"
description = "dateutils for the Snake Corporation"
license = { text = "Snake Corp Software Licence Agreement" }

[tool.black]
line-length = 79
