[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "snake-shop-sales"
version = "48.2.78"
description = "Sales Package for the Snake Shop Corporation"
license = {text = "Snake Shop Software Licence Agreement"}

[tool.black]
line-length=79