[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "snake-corp-sales"
version = "48.2.78"
description = "Sales Package for the Snake Corporation"
license = { text = "Snake Corp Software Licence Agreement" }

[tool.black]
line-length = 79
