[general]
chat_models = ["gpt-3.5", "gpt-3.5-turbo", "gpt-4"]
model = "text-davinci-003"
max_tokens = 2200
temperature = 0

[prompts]
instructions = """
Remove personally identifiable information, only show the date, and replace all swear words with "😤"
"""
